#pragma once

// BGMI [3.4.0] x64 SDK Generated by @DARKESPYT - @USIR_DIED_REAL


namespace SDK
{
//----------------------------- | JOIN FOR MORE : @DARKESPYT |-----------------------------
//Script Structs
//----------------------------- | JOIN FOR MORE : @DARKESPYT |-----------------------------

// UserDefinedStruct BP_STRUCT_LocalizationText_Index_type.BP_STRUCT_LocalizationText_Index_type
// 0x0010
struct FBP_STRUCT_LocalizationText_Index_type
{
	int                                                KeyIndex_0_20AD6700064CC15476CD5A6006F22118;              // 0x0000(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     Key_1_4122C900056D76E21C2FCE3C02E6BD69;                   // 0x0004(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
};

}

//JOIN HERE : @DARKESPYT
//JOIN HERE : @DARKESPYT
//JOIN HERE : @DARKESPYT
