#pragma once

// BGMI [3.4.0] x64 SDK Generated by @DARKESPYT - @USIR_DIED_REAL


namespace SDK
{
//----------------------------- | JOIN FOR MORE : @DARKESPYT |-----------------------------
//Script Structs
//----------------------------- | JOIN FOR MORE : @DARKESPYT |-----------------------------

// UserDefinedStruct BP_STRUCT_LocalizationText_en_type.BP_STRUCT_LocalizationText_en_type
// 0x0010
struct FBP_STRUCT_LocalizationText_en_type
{
	int                                                KeyIndex_2_5EB45DC069BE27470A962D7205D6B998;              // 0x0000(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     Value_4_28CFB4C0620053F1320833900F38F315;                 // 0x0004(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
};

}

//JOIN HERE : @DARKESPYT
//JOIN HERE : @DARKESPYT
//JOIN HERE : @DARKESPYT
