#pragma once

// BGMI [3.4.0] x64 SDK Generated by @DARKESPYT - @USIR_DIED_REAL

namespace SDK
{
//----------------------------- | JOIN FOR MORE : @DARKESPYT |-----------------------------
//Script Structs
//----------------------------- | JOIN FOR MORE : @DARKESPYT |-----------------------------

// UserDefinedStruct BP_STRUCT_Client90FPSMapping_type.BP_STRUCT_Client90FPSMapping_type
// 0x0018
struct FBP_STRUCT_Client90FPSMapping_type
{
	int                                                ID_0_2DEE08006382BF702F6484140ACB00E4;                    // 0x0000(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData00[0x4];                                       // 0x0004(0x0004) MISSED OFFSET
	struct FString                                     ModelNames_1_44BD5E0053F958C20DFB3D8B01157CA3;            // 0x0008(0x0010) (Edit, BlueprintVisible, ZeroConstructor)
};

}

//JOIN HERE : @DARKESPYT
//JOIN HERE : @DARKESPYT
//JOIN HERE : @DARKESPYT
