#pragma once

// BGMI [3.4.0] x64 SDK Generated by @DARKESPYT - @USIR_DIED_REAL

namespace SDK
{
//----------------------------- | JOIN FOR MORE : @DARKESPYT |-----------------------------
//Script Structs
//----------------------------- | JOIN FOR MORE : @DARKESPYT |-----------------------------

// UserDefinedStruct BP_STRUCT_FontStylePreset_type.BP_STRUCT_FontStylePreset_type
// 0x0020
struct FBP_STRUCT_FontStylePreset_type
{
	struct FString                                     FontName_0_44EF324019A535D53F56006B0E9E4B85;              // 0x0000(0x0010) (Edit, BlueprintVisible, ZeroConstructor)
	struct FString                                     FontPath_1_008D9540303E41453F57D0D90E9C6518;              // 0x0010(0x0010) (Edit, BlueprintVisible, ZeroConstructor)
};

}

//JOIN HERE : @DARKESPYT
//JOIN HERE : @DARKESPYT
//JOIN HERE : @DARKESPYT
