#pragma once

// BGMI [3.4.0] x64 SDK Generated by @DARKESPYT - @USIR_DIED_REAL

namespace SDK
{
//----------------------------- | JOIN FOR MORE : @DARKESPYT |-----------------------------
//Script Structs
//----------------------------- | JOIN FOR MORE : @DARKESPYT |-----------------------------

// UserDefinedStruct BP_STRUCT_StatEventType_type.BP_STRUCT_StatEventType_type
// 0x0014
struct FBP_STRUCT_StatEventType_type
{
	struct FString                                     DisplayName_0_7D516B402CBFB7AB2A776EB00D8D1405;           // 0x0000(0x0010) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                id_1_49A788C0256E4AF90B9DAE5205E4F254;                    // 0x0010(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
};

}

//JOIN HERE : @DARKESPYT
//JOIN HERE : @DARKESPYT
//JOIN HERE : @DARKESPYT
